### ISSUE TITLE
error: void function 'extDefPush' should not return a value

### ISSUE THREAD

**Issue by ryandesign** [RTimothyEdwards/magic#156]
magic 8.3.289 doesn't build on macOS 10.15:

```
ExtMain.c:333:5: error: void function 'extDefPush' should not return a value [-Wreturn-type]
    return (0);
    ^      ~~~
```

**Comment by RTimothyEdwards** [comment]
Okay, I have fixed this.
