### ISSUE TITLE
error: conflicting types for 'LefReadLayerSection'

### ISSUE THREAD

**Issue by ryandesign** [RTimothyEdwards/magic#154]
magic 8.3.285 and 8.3.286 no longer build on macOS 10.15:

```
lefRead.c:1822:7: warning: implicit declaration of function 'LefReadLayerSection' is invalid in C99 [-Wimplicit-function-declaration]
                    LefReadLayerSection(f, tsave, keyword, lefl);
                    ^
```
```
lefRead.c:2499:1: error: conflicting types for 'LefReadLayerSection'
LefReadLayerSection(f, lname, mode, lefl)
^
lefRead.c:1822:7: note: previous implicit declaration is here
                    LefReadLayerSection(f, tsave, keyword, lefl);
                    ^
```

magic 8.3.284 and earlier build fine on macOS 10.15.

**Comment by RTimothyEdwards** [comment]
Fixed and pushed to opencircuitdesign.com, thanks!

**Comment by ryandesign** [comment]
Thanks!
